### ISSUE TITLE
bug: React Output Target, incorrect JSX path on generated file

### ISSUE THREAD

**Issue by dpellier** [stenciljs/output-targets#404] opened 2023-12-04 14:43 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.7.2

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.5.3

### Current Behavior

I've followed https://stenciljs.com/docs/react documentation to initiate a project with a stencil-lib and a react-lib.

Then I've set the `includeImportCustomElements` option to true on the config.

After a new build, if I check the generated `proxiesFile`, the JSX import point to the wrong place:
```
// react-library/lib/components/stencil-generated/index.ts

/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from 'stencil-library/dist/components';

import { defineCustomElement as defineMyFormField } from 'stencil-library/dist/components/my-form-field.js';
import { defineCustomElement as defineMyText } from 'stencil-library/dist/components/my-text.js';

export const MyFormField = /*@__PURE__*/createReactComponent<JSX.MyFormField, HTMLMyFormFieldElement>('my-form-field', undefined, undefined, defineMyFormField);
export const MyText = /*@__PURE__*/createReactComponent<JSX.MyText, HTMLMyTextElement>('my-text', undefined, undefined, defineMyText);
```

<img width="895" alt="Capture d’écran 2023-12-04 à 15 33 06" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/1390934/ff131ae4-84b1-46b5-b07d-5d2682c9bf54">

### Expected Behavior

The `import type { JSX }` should default to its correct path
(in my case, it would be `import type { JSX } from 'stencil-library';`

### Steps to Reproduce

- Follow the guide https://stenciljs.com/docs/react
- Update the react output config to use `includeImportCustomElements`
- Check the generated file

### Code Reproduction URL

https://github.com/dpellier/stencil-react-issue/tree/main

### Additional Information

You can see the whole project in the given reproduction link.

Quick overview of stencil.config:
```
import { Config } from '@stencil/core';
import { reactOutputTarget } from '@stencil/react-output-target';

export const config: Config = {
  namespace: 'stencil-library',
  outputTargets: [
    {
      type: 'dist-custom-elements',
      generateTypeDeclarations: true,
    },
    {
      type: 'www',
      serviceWorker: null,
    },
    reactOutputTarget({
      componentCorePackage: 'stencil-library',
      proxiesFile: '../react-library/lib/components/stencil-generated/index.ts',
      includeImportCustomElements: true,
      customElementsDir: 'dist/components',
    }),
  ],
  testing: {
    browserHeadless: "new",
  },
};
```

and stencil-library package.json:
```
{
  "name": "stencil-library",
  "version": "0.0.1",
  "description": "Stencil Component Starter",
  "main": "dist/index.cjs.js",
  "module": "dist/index.js",
  "es2015": "dist/esm/index.js",
  "es2017": "dist/esm/index.js",
  "types": "dist/types/index.d.ts",
  "collection": "dist/collection/collection-manifest.json",
  "collection:main": "dist/collection/index.js",
  "files": [
    "dist/",
    "loader/"
  ],
  "scripts": {
    "build": "stencil build --docs",
    "start": "stencil build --dev --watch --serve",
    "test": "stencil test --spec --e2e",
    "test.watch": "stencil test --spec --e2e --watchAll",
    "generate": "stencil generate"
  },
  "dependencies": {
    "@stencil/core": "^4.7.0"
  },
  "devDependencies": {
    "@stencil/react-output-target": "^0.5.3",
    "@types/jest": "^29.5.6",
    "@types/node": "^16.18.11",
    "jest": "^29.7.0",
    "jest-cli": "^29.7.0",
    "puppeteer": "21.1.1"
  },
  "license": "MIT"
}
```

**Comment by karthikeyan-arumugam-1558** [comment] 2024-04-03 12:31
@dpellier did you manage to solve this?

**Comment by karthikeyan-arumugam-1558** [comment] 2024-04-03 12:38
@liamdebeasi would be great if you can have a look at this

**Comment by andresgutgon** [comment] 2024-04-05 14:03
Same issue from a fresh project

**Comment by andresgutgon** [comment] 2024-04-05 14:43
Also has a related error on the react part. We have Typescript in the react project. When checking with `tsc --noEmit`

We get this error on react webcomponents proxy files
<img width="1192" alt="image" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/49499/25fd6cf8-3d04-4405-846a-9b461515f95c">


We solved this issue setting [strictNullChecks](https://www.typescriptlang.org/tsconfig#strictNullChecks) to `false` in our Typescript `tsconfig`

```json
{
  "compilerOptions": {
    "strictNullChecks": false
  }
}
```

But this is not ideal. Could be this part of the same issue or should I open a new one. Thanks!

**Comment by karthikeyan-arumugam-1558** [comment] 2024-04-05 15:36
@andresgutgon, did you not have to set `customElementsDir` to _dist/components_ in your `reactOutputTarget`? As in
```
reactOutputTarget({
  componentCorePackage: 'stencil-library',
  proxiesFile: '../react-library/lib/components/stencil-generated/index.ts',
  includeImportCustomElements: true,
  customElementsDir: 'dist/components',
}),
```
Unless I do this, all imports fail. With this, only the JSX import fails.
I use _@stencil/react-output-target v0.5.3_ and _@stencil/core v4.9.0_.

**Comment by andresgutgon** [comment] 2024-04-05 15:39
Nop, I didn't add `customElementDir` I just started today following [official docs](https://stenciljs.com/docs/react#adding-the-react-output-target)
<img width="881" alt="image" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/49499/7cda3310-b81f-4e1c-8f58-e8a85eb10390">

**Comment by karthikeyan-arumugam-1558** [comment] 2024-04-23 01:43
@liamdebeasi @splitinfinities @rwaskiewicz would be great if you can have a look at this

**Comment by crrobinson14** [comment] 2024-07-25 17:37
We are setting `customElementsDir: 'dist/components'` as some noted above. That helped all of the `import { defineCustomElement as defineXYZ } from '@scope/pkg/dist/components/xyz.js';` entries. But we are also still getting the `import type { JSX } from '@scope/pkg/dist/components';` issue. Chiming in here to note that for our fix we change `dist/components` to `dist/types` on this line.

I can't for the life of me figure out where this line comes from in the first place. It doesn't appear to be a string in the stencil or react-output-target modules so I assume it's something generated/computed by some internal step rather than a simple string template. If this attention doesn't warrant attention from the core team, perhaps somebody could at least weigh in on guidance on how this file gets generated in the first place? Perhaps we could work out a hack if we knew some likely paths to explore...

**Comment by christian-bromann** [comment] 2024-10-14 21:00
Duplicate of #404

**Closed as completed by christian-bromann** 2024-10-14 21:00 UTC
Labels: type: bug, help wanted
